// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSz4Zal_yP0AnBygmtUDCc8GJ4HFrmcv8',
    appId: '1:73744018745:web:fc3e38f59a1642867f0ce8',
    messagingSenderId: '73744018745',
    projectId: 'akemha-e816a',
    authDomain: 'akemha-e816a.firebaseapp.com',
    storageBucket: 'akemha-e816a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQ1yZf3sp6sgaZASNOxckh9JQm_CZNR4',
    appId: '1:73744018745:android:65754a78d7e3ac1d7f0ce8',
    messagingSenderId: '73744018745',
    projectId: 'akemha-e816a',
    storageBucket: 'akemha-e816a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQsFlqpU9S0inPnG_ME7mwWKyXVXG6cGQ',
    appId: '1:73744018745:ios:40bb7cb262a1c9277f0ce8',
    messagingSenderId: '73744018745',
    projectId: 'akemha-e816a',
    storageBucket: 'akemha-e816a.appspot.com',
    iosBundleId: 'com.example.akemha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQsFlqpU9S0inPnG_ME7mwWKyXVXG6cGQ',
    appId: '1:73744018745:ios:40bb7cb262a1c9277f0ce8',
    messagingSenderId: '73744018745',
    projectId: 'akemha-e816a',
    storageBucket: 'akemha-e816a.appspot.com',
    iosBundleId: 'com.example.akemha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSz4Zal_yP0AnBygmtUDCc8GJ4HFrmcv8',
    appId: '1:73744018745:web:c253bff1893ab2367f0ce8',
    messagingSenderId: '73744018745',
    projectId: 'akemha-e816a',
    authDomain: 'akemha-e816a.firebaseapp.com',
    storageBucket: 'akemha-e816a.appspot.com',
  );
}
